#store sensitive credentials securely (Base64 encoding)
apiVersion: v1
kind: Secret
metadata:
  name: echo-api-secret
type: Opaque
data:
  #Git Bash: echo -n "my-api-secret-key-2026" | base64 
  #-n in order to handle hidden newline elements (\n) during terminal encoding
  API_SECRET_KEY: bXktYXBpLXNlY3JldC1rZXktMjAyNg==


